# Generated by Django 3.2.18 on 2023-07-06 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydatas',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='p_templates',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='email',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='github',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='job',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='p_templates',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='like_users',
        ),
        migrations.AddField(
            model_name='mydatas',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p_templates',
            name='like_users',
            field=models.ManyToManyField(related_name='like_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='P_exampleuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField()),
                ('stack', models.ManyToManyField(related_name='template_stacks', to='portfolios.TechStack')),
            ],
        ),
    ]
