# Generated by Django 3.2.18 on 2023-07-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20230706_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='content',
            new_name='career_content',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='content',
            new_name='link_content',
        ),
        migrations.RenameField(
            model_name='pjts',
            old_name='content',
            new_name='pjst_content',
        ),
    ]
