# Generated by Django 3.2.18 on 2023-07-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20230710_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjts',
            old_name='pjst_content',
            new_name='pjts_content',
        ),
    ]
