# Generated by Django 3.2.18 on 2023-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_rename_pjst_content_pjts_pjts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjts',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pjts',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
