# Generated by Django 3.2.18 on 2023-07-26 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0005_auto_20230726_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_templates',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
