# Generated by Django 3.2.18 on 2023-07-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pay_stutus',
            new_name='pay_status',
        ),
    ]
