# Generated by Django 3.2.18 on 2023-07-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_pay_stutus_user_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pay_status',
        ),
    ]
